// File generated by FlutterFire CLI.
// ignore_for_file: type=lint


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6zI9Yp2_-gw8qi3mC1-j3mk38JoyUZJo',
    appId: '1:729262386456:web:930a661961c06f2f6b026d',
    messagingSenderId: '729262386456',
    projectId: 'smartholticulture4',
    authDomain: 'smartholticulture4.firebaseapp.com',
    databaseURL: 'https://smartholticulture4-default-rtdb.firebaseio.com',
    storageBucket: 'smartholticulture4.appspot.com',
    measurementId: 'G-XC5KG95BGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAczF4v8_WEQzcqat35S5vZc3OxjW3Tj3U',
    appId: '1:729262386456:android:422e0ead3de3440c6b026d',
    messagingSenderId: '729262386456',
    projectId: 'smartholticulture4',
    databaseURL: 'https://smartholticulture4-default-rtdb.firebaseio.com',
    storageBucket: 'smartholticulture4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3tHajA3OQQ48AXOyw6fdRwIjJeV-iees',
    appId: '1:729262386456:ios:422db1a65bca7b726b026d',
    messagingSenderId: '729262386456',
    projectId: 'smartholticulture4',
    databaseURL: 'https://smartholticulture4-default-rtdb.firebaseio.com',
    storageBucket: 'smartholticulture4.appspot.com',
    iosBundleId: 'com.example.smartHolticulture44',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3tHajA3OQQ48AXOyw6fdRwIjJeV-iees',
    appId: '1:729262386456:ios:422db1a65bca7b726b026d',
    messagingSenderId: '729262386456',
    projectId: 'smartholticulture4',
    databaseURL: 'https://smartholticulture4-default-rtdb.firebaseio.com',
    storageBucket: 'smartholticulture4.appspot.com',
    iosBundleId: 'com.example.smartHolticulture44',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6zI9Yp2_-gw8qi3mC1-j3mk38JoyUZJo',
    appId: '1:729262386456:web:1427b41a5fef05ea6b026d',
    messagingSenderId: '729262386456',
    projectId: 'smartholticulture4',
    authDomain: 'smartholticulture4.firebaseapp.com',
    databaseURL: 'https://smartholticulture4-default-rtdb.firebaseio.com',
    storageBucket: 'smartholticulture4.appspot.com',
    measurementId: 'G-GFEBPYZ3BB',
  );
}
